stages:
  preprocess_train:
    cmd: python src/preprocess_data.py -s 1
  preprocess_test:
    cmd: python src/preprocess_data.py -s 0
  train_model:
    cmd: python src/train_model.py -m models/xgb_v2.joblib
  test_model:
    cmd: python src/test_model.py -m models/xgb_v2.joblib